version: '3'

services:
  web:
    image: php:8.3.0-apache
    ports:
      - 8818:80
    volumes:
      - ./webapp/public:/var/www/html
      - ./webapp/private:/var/www/private
    environment:
      - SECRET_KEY=mysalt1234567890

  attack:
    container_name: hash_extender
    build: .
    tty: true
